name: FirstName

on: 
  workflow_dispatch:
  
  jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Simple shell command step
          run: echo Hello from Step 1
        - name: Simple shell command step
          run: echo Hello from Step 2

second-job:
      runs-on: ubuntu-latest
      steps:
        - name: Simple shell command step
          run: echo Hello world

third-job:
      runs-on: ubuntu-latest
      needs: [second-job]
      steps:
        - name: Simple shell command step
          run: echo Hello world
